version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.jgrapht:jgrapht-core"
        versions: ">= 1.5.0"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
