dist: trusty
language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
before_install:
  - if [ -e $JAVA_HOME/lib/security/cacerts ]; then ln -sf /etc/ssl/certs/java/cacerts $JAVA_HOME/lib/security/cacerts; fi
install: true
script: mvn -B -e -s .travis-settings.xml -Prelease -Dgpg.skip=true verify
before_cache: "find $HOME/.m2 -name '*-SNAPSHOT' -a -type d -print0 | xargs -0 rm -rf"
jobs:
  include:
    - if: repo = "veithen/phos" AND branch = master AND type = push
      stage: deploy
      script: mvn -B -e -s .travis-settings.xml -Prelease -Dgpg.skip=true -DskipTests=true deploy
      env:
        - secure: "serxV7Iubml1f+0o3LNWV3Jkh3tUUoDudR20Yvleeu6c/eYALHn3gPwf20TwJTrUObXf36zfwDC4U5ps6WRGW1hIUYIeUy2aFCGL3iRtniwuXPiUv3+yJ3i61rhrei9EYhoThE89iPGJarvzbxE2B3ePlktd/kzka72bKj8QSQ1UuRfPtFSmWC7W/IllRtjS6hYBNmZV86uGiF3A74JSv4Uef8h/KQCS7dFKcAYM9kXTa/azaHryKIY6uZIYHLHP/0kv6QySbTgUu4jjeypz+loV8aBNhbd98b3ZjeDmm0L5JKN85eS0DFd79orEzGsUJMpekQrSHMzSg3XmI9OVwTZ4fkLSCt31hEHCZZP1ikf1TnmwBSoj0UGkCXSNoQrDjTgP1PLMF+eXLeDGRy+1luGzhmT8noEvm5WqVd0iQgl2eDgEYhoIoNiG/cLNPsp3/2zL/m+8dD9OHkxrFRGnR6wp9qudflgkCHnIzJ4lTJAkGWesKb02noKslNwDbFQ3mUK4pPX6miuOul/b9vxh0s2BNfgoG8tqXk5SGD5YZzGSeqfud7aENfkkat0iwRmuwXgl/2eMeESgadc5NobOLvKI9iOQRcWNeB4Qhhr47wsJCsgg6sP3NxdDRDuq5ATh2sF+IlIJQxGFNxFD9tfpf3FbkurlhfyTlYqQpKGQw0I="
cache:
  directories:
    - $HOME/.m2
